from pathlib import Path, PurePosixPath
from typing import NoReturn

CFG_SYSROOT: str
CFG_TOOLCHAIN: str
EXIT_BUILD_FAILURE: int
EXIT_MISSING_DEP: int

class _DockerConfig:
    image: str

class _Log:
    def info(self, msg: str) -> None: ...
    def success(self, msg: str) -> None: ...
    def warning(self, msg: str, code: int | None = None) -> None: ...
    def error(self, msg: str, hint: str | None = None) -> None: ...
    def fatal(self, msg: str, code: int = 1, hint: str | None = None) -> NoReturn: ...

class _Config:
    @property
    def machine(self) -> str: ...
    @property
    def deployment_mode(self) -> str: ...
    @property
    def memory_size(self) -> str: ...
    def get(self, key: str, default: str | None = None) -> str | None: ...

class ZScript:
    config: _Config
    repo_root: Path
    targets: list[str]
    nanvix_dir: Path
    docker: _DockerConfig | None
    def translate_path(self, host_path: Path) -> PurePosixPath | Path: ...
    def docker_config(self, image: str) -> _DockerConfig: ...
    def setup(self) -> None: ...
    def build(self) -> None: ...
    def test(self) -> None: ...
    def release(self) -> None: ...
    def clean(self) -> None: ...
    def run(self, *args: str, cwd: Path | None = None, env: dict[str, str] | None = None, docker: bool = ..., timeout: int | None = None) -> None: ...
    def make_initrd(self, binary_name: str) -> Path: ...
    @classmethod
    def main(cls, *, repo_root: Path | None = None) -> None: ...

log: _Log
